// "use client"
import Footer from "@/components/layouts/mainLayout/footer/Footer";
import "../styles/globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";


import MainNav from "@/components/layouts/mainLayout/mainNav/MainNav";
import { Metadata } from "next";
import NextAuthSessionProvider from "@/components/sessionProvider";

export const metadata: Metadata = {
  title: "Tarkhineh",
  description: "Generated by Next.js",
  manifest: "/manifest.json",
  icons: { apple: "/icons/android-chrome-192x192.png" },
  themeColor: "#417F56",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {



  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          <section className="relative">
            <MainNav />
            <section className="min-h-screen">{children}</section>
            <Footer />
          </section>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
