"use client"

import Footer from "@/components/layouts/mainLayout/footer/Footer";
import "../styles/globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import toast, { Toaster } from "react-hot-toast";

import MainNav from "@/components/layouts/mainLayout/mainNav/MainNav";
import { Metadata } from "next";
import { SessionProvider, useSession } from "next-auth/react";

export const metadata: Metadata = {
  title: "Tarkhineh",
  description: "Generated by Next.js",
  manifest: "/manifest.json",
  icons: { apple: "/icons/android-chrome-192x192.png" },
  themeColor: "#417F56",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {



  return (
    <html lang="en">
      <body>
        <Toaster />
        <SessionProvider>
          <section className="relative">
            <MainNav />
            <section className="min-h-screen">{children}</section>
            <Footer />
          </section>
        </SessionProvider>
      </body>
    </html>
  );
}
